package s3storage

import (
	"fmt"

	"nimbus/internal/db"
)

// MigrateOrphanS3Keys cleans up SSH keys auto-minted by past S3 storage
// deploys. Idempotent backfill called at startup from main.go.
//
// Behavior:
//   - The SSH key tied to the live storage VM (if any) is marked
//     `system_generated=true` and pinned to s3_storage.ssh_key_id when
//     the link is missing. This back-fills the cleanup machinery for
//     storage rows that pre-date the SSHKeyID column.
//   - SSH keys whose name matches the S3-deploy naming convention
//     (`nimbus-nimbus-s3-%`) but no longer correspond to any live
//     storage row are hard-deleted from the user's vault — they were
//     orphans from failed prior deploys and cannot be SSHed to anything
//     useful.
//
// Safe to run on every boot; on a clean install with no S3 history it's
// a no-op. On a pre-cleanup install with a live storage VM and N failed
// past attempts, it marks 1, deletes N.
//
// Returns (cleaned, marked) where cleaned is the count of orphan rows
// hard-deleted and marked is the count of SSH keys newly flagged
// system_generated by this run.
func (s *Service) MigrateOrphanS3Keys() (cleaned int, marked int, err error) {
	var candidates []db.SSHKey
	if err := s.db.Where("name LIKE ?", "nimbus-nimbus-s3-%").Find(&candidates).Error; err != nil {
		return 0, 0, fmt.Errorf("scan s3 ssh-key candidates: %w", err)
	}
	if len(candidates) == 0 {
		return 0, 0, nil
	}

	// Resolve the live storage VM's SSH key id, preferring the explicit
	// link and falling back to the VM-table join for legacy rows.
	var liveKeyID uint
	var storage db.S3Storage
	if dbErr := s.db.First(&storage).Error; dbErr == nil {
		switch {
		case storage.SSHKeyID != nil:
			liveKeyID = *storage.SSHKeyID
		case storage.VMRowID != nil:
			var vm db.VM
			if vmErr := s.db.First(&vm, *storage.VMRowID).Error; vmErr == nil && vm.SSHKeyID != nil {
				liveKeyID = *vm.SSHKeyID
				// Backfill the link on the storage row while we have it.
				if uErr := s.db.Model(&db.S3Storage{}).Where("id = ?", storage.ID).
					Update("ssh_key_id", liveKeyID).Error; uErr != nil {
					return cleaned, marked, fmt.Errorf("backfill s3_storage.ssh_key_id: %w", uErr)
				}
			}
		}
	}

	for _, k := range candidates {
		if k.ID == liveKeyID {
			if !k.SystemGenerated {
				if uErr := s.db.Model(&db.SSHKey{}).Where("id = ?", k.ID).
					Update("system_generated", true).Error; uErr != nil {
					return cleaned, marked, fmt.Errorf("mark key %d (%s) system-generated: %w", k.ID, k.Name, uErr)
				}
				marked++
			}
			continue
		}
		// Orphan from a failed deploy. Hard-delete (Unscoped) so the
		// row doesn't sit around as a soft-deleted ghost reachable via
		// a name-collision insert.
		if dErr := s.db.Unscoped().Delete(&k).Error; dErr != nil {
			return cleaned, marked, fmt.Errorf("delete orphan key %d (%s): %w", k.ID, k.Name, dErr)
		}
		cleaned++
	}
	return cleaned, marked, nil
}
