// Command gx10-worker is the GX10-side daemon for Nimbus's GPU plane.
//
// It does one thing in a loop: poll Nimbus for a queued job, run it inside
// a Docker container with --gpus all, stream stdout+stderr back, and post
// the terminal status. There is no scheduling, no retry beyond Docker's,
// no parallelism — one job at a time, FIFO.
//
// Auth is a pre-shared bearer token in `Authorization: Bearer <token>`.
// The token is generated by Nimbus and copy-pasted into this worker's env
// once during install (see scripts/gx10/install-worker.sh).
//
// Cross-compile for the GX10 (ARM64):
//
//	GOOS=linux GOARCH=arm64 go build -o gx10-worker ./cmd/gx10-worker
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

// Tuning knobs. All overridable via env so an operator can iterate without
// rebuilding the binary.
var (
	pollInterval  = envDuration("GX10_POLL_INTERVAL", 3*time.Second)
	httpTimeout   = envDuration("GX10_HTTP_TIMEOUT", 30*time.Second)
	logFlushDelay = envDuration("GX10_LOG_FLUSH_DELAY", 1*time.Second)
	logFlushBytes = envInt("GX10_LOG_FLUSH_BYTES", 4*1024)
	dockerCmd     = envOr("GX10_DOCKER", "docker")
)

func main() {
	nimbusURL := strings.TrimRight(os.Getenv("NIMBUS_URL"), "/")
	token := os.Getenv("NIMBUS_WORKER_TOKEN")
	workerID := os.Getenv("GX10_WORKER_ID")
	if workerID == "" {
		hostname, _ := os.Hostname()
		workerID = "gx10-" + hostname
	}
	if nimbusURL == "" || token == "" {
		log.Fatalf("NIMBUS_URL and NIMBUS_WORKER_TOKEN are required")
	}

	client := &http.Client{Timeout: httpTimeout}
	worker := &worker{
		nimbusURL: nimbusURL,
		token:     token,
		workerID:  workerID,
		http:      client,
	}

	ctx, cancel := signalContext()
	defer cancel()

	log.Printf("gx10-worker starting (nimbus=%s worker=%s poll=%s)",
		nimbusURL, workerID, pollInterval)

	t := time.NewTicker(pollInterval)
	defer t.Stop()
	for {
		// Try once immediately so the first job lands without waiting a
		// full pollInterval after start.
		worker.tick(ctx)
		select {
		case <-ctx.Done():
			log.Printf("shutdown requested")
			return
		case <-t.C:
		}
	}
}

type worker struct {
	nimbusURL string
	token     string
	workerID  string
	http      *http.Client
}

// tick performs one claim attempt. If it returns a job, runs it to terminal
// state synchronously (one-job-at-a-time is the design). Errors are logged
// and the next tick retries.
func (w *worker) tick(ctx context.Context) {
	job, err := w.claim(ctx)
	if err != nil {
		log.Printf("claim error: %v", err)
		return
	}
	if job == nil {
		return // queue empty
	}
	log.Printf("claimed job id=%d image=%s", job.ID, job.Image)
	if err := w.runJob(ctx, job); err != nil {
		log.Printf("job %d failed locally: %v", job.ID, err)
	}
}

// claimedJob mirrors the subset of gpuJobView the worker needs.
type claimedJob struct {
	ID      uint              `json:"id"`
	Image   string            `json:"image"`
	Command string            `json:"command"`
	Env     map[string]string `json:"env,omitempty"`
}

func (w *worker) claim(ctx context.Context) (*claimedJob, error) {
	req, err := w.newRequest(ctx, http.MethodPost, "/api/gpu/worker/claim", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("X-Worker-ID", w.workerID)
	resp, err := w.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close() //nolint:errcheck

	if resp.StatusCode == http.StatusNoContent {
		return nil, nil
	}
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return nil, fmt.Errorf("claim returned %d: %s", resp.StatusCode, string(body))
	}

	// Nimbus wraps responses in {"success":true,"data":{...}} — decode that.
	var env struct {
		Data claimedJob `json:"data"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&env); err != nil {
		return nil, fmt.Errorf("decode claim response: %w", err)
	}
	return &env.Data, nil
}

// runJob invokes docker run with --gpus all, streams logs, and posts the
// terminal status. The container is run synchronously; this function does
// not return until the container exits or ctx is cancelled.
func (w *worker) runJob(ctx context.Context, job *claimedJob) error {
	args := []string{"run", "--rm", "--gpus", "all"}
	for k, v := range job.Env {
		args = append(args, "-e", fmt.Sprintf("%s=%s", k, v))
	}
	args = append(args, job.Image)
	if cmd := strings.TrimSpace(job.Command); cmd != "" {
		// The command is a single shell string — use sh -c so quoting and
		// pipes work as the user expects.
		args = append(args, "sh", "-c", cmd)
	}

	dockerProc := exec.CommandContext(ctx, dockerCmd, args...)
	stdoutPipe, err := dockerProc.StdoutPipe()
	if err != nil {
		w.reportTerminal(ctx, job.ID, "failed", -1, "", "stdout pipe: "+err.Error())
		return err
	}
	stderrPipe, err := dockerProc.StderrPipe()
	if err != nil {
		w.reportTerminal(ctx, job.ID, "failed", -1, "", "stderr pipe: "+err.Error())
		return err
	}
	if err := dockerProc.Start(); err != nil {
		w.reportTerminal(ctx, job.ID, "failed", -1, "", "docker start: "+err.Error())
		return err
	}

	// Stream stdout and stderr through a single coalescing buffer that
	// flushes to Nimbus on size threshold or after a quiet period. Tag
	// stderr lines with a prefix so callers can disambiguate.
	flusher := newLogFlusher(ctx, w, job.ID)
	doneOut := make(chan struct{})
	doneErr := make(chan struct{})
	go func() { defer close(doneOut); copyTo(flusher, stdoutPipe, "") }()
	go func() { defer close(doneErr); copyTo(flusher, stderrPipe, "") }()

	waitErr := dockerProc.Wait()
	<-doneOut
	<-doneErr
	flusher.flush(true)

	exitCode := 0
	status := "succeeded"
	errMsg := ""
	if waitErr != nil {
		var exitErr *exec.ExitError
		if errors.As(waitErr, &exitErr) {
			exitCode = exitErr.ExitCode()
		} else {
			exitCode = -1
			errMsg = waitErr.Error()
		}
		status = "failed"
	}
	w.reportTerminal(ctx, job.ID, status, exitCode, "", errMsg)
	return waitErr
}

// reportTerminal posts the final status. Logged on failure so the operator
// can debug; the job stays in `running` and the next ReapStuckJobs pass
// will catch it.
func (w *worker) reportTerminal(ctx context.Context, jobID uint, status string, exitCode int, artifact, errMsg string) {
	body, _ := json.Marshal(map[string]any{
		"status":        status,
		"exit_code":     exitCode,
		"artifact_path": artifact,
		"error_msg":     errMsg,
	})
	req, err := w.newRequest(ctx, http.MethodPost,
		fmt.Sprintf("/api/gpu/worker/jobs/%d/status", jobID),
		bytes.NewReader(body))
	if err != nil {
		log.Printf("status post: build request: %v", err)
		return
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := w.http.Do(req)
	if err != nil {
		log.Printf("status post: %v", err)
		return
	}
	defer resp.Body.Close() //nolint:errcheck
	if resp.StatusCode >= 300 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		log.Printf("status post returned %d: %s", resp.StatusCode, string(body))
	}
}

// postLogs ships a chunk of bytes to Nimbus's append-logs endpoint. Caller
// should batch — each call is a full HTTP round-trip.
func (w *worker) postLogs(ctx context.Context, jobID uint, chunk []byte) error {
	req, err := w.newRequest(ctx, http.MethodPost,
		fmt.Sprintf("/api/gpu/worker/jobs/%d/logs", jobID),
		bytes.NewReader(chunk))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/octet-stream")
	resp, err := w.http.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close() //nolint:errcheck
	if resp.StatusCode >= 300 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return fmt.Errorf("logs post returned %d: %s", resp.StatusCode, string(body))
	}
	return nil
}

// logFlusher coalesces small writes into network-friendly chunks. Flushes
// on byte threshold OR after a quiet period (whichever comes first).
type logFlusher struct {
	ctx     context.Context
	w       *worker
	jobID   uint
	buf     bytes.Buffer
	timer   *time.Timer
	stopped bool
}

func newLogFlusher(ctx context.Context, w *worker, jobID uint) *logFlusher {
	f := &logFlusher{ctx: ctx, w: w, jobID: jobID}
	f.timer = time.AfterFunc(logFlushDelay, func() {
		f.flush(false)
	})
	return f
}

func (f *logFlusher) Write(p []byte) (int, error) {
	if f.stopped {
		return len(p), nil
	}
	f.buf.Write(p)
	if f.buf.Len() >= logFlushBytes {
		f.flush(false)
		return len(p), nil
	}
	if f.timer != nil {
		f.timer.Reset(logFlushDelay)
	}
	return len(p), nil
}

func (f *logFlusher) flush(final bool) {
	if final {
		f.stopped = true
		if f.timer != nil {
			f.timer.Stop()
		}
	}
	if f.buf.Len() == 0 {
		return
	}
	chunk := make([]byte, f.buf.Len())
	copy(chunk, f.buf.Bytes())
	f.buf.Reset()
	if err := f.w.postLogs(f.ctx, f.jobID, chunk); err != nil {
		log.Printf("log flush failed: %v", err)
	}
}

// copyTo reads from r line-by-line so we never split on a UTF-8 boundary
// mid-character. _prefix is reserved for future stderr tagging — currently
// we just write through to avoid extra allocations.
func copyTo(dst io.Writer, r io.Reader, _prefix string) {
	buf := make([]byte, 4096)
	for {
		n, err := r.Read(buf)
		if n > 0 {
			_, _ = dst.Write(buf[:n])
		}
		if err != nil {
			return
		}
	}
}

// newRequest constructs an HTTP request with the bearer token attached.
func (w *worker) newRequest(ctx context.Context, method, path string, body io.Reader) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, method, w.nimbusURL+path, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+w.token)
	req.Header.Set("Accept", "application/json")
	return req, nil
}

// signalContext returns a context that's cancelled on SIGINT / SIGTERM so
// the systemd unit can stop the worker cleanly.
func signalContext() (context.Context, context.CancelFunc) {
	ctx, cancel := context.WithCancel(context.Background())
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-c
		cancel()
	}()
	return ctx, cancel
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func envDuration(key string, fallback time.Duration) time.Duration {
	if v := os.Getenv(key); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return fallback
}

func envInt(key string, fallback int) int {
	if v := os.Getenv(key); v != "" {
		var n int
		if _, err := fmt.Sscanf(v, "%d", &n); err == nil {
			return n
		}
	}
	return fallback
}
