package provision

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/kdomanski/iso9660"
)

// CIDataLabel is the volume label cloud-init's NoCloud datasource
// scans for. Must be exactly "cidata" (or "CIDATA") for cloud-init
// to find the ISO. We use lowercase to match Proxmox's convention.
const CIDataLabel = "cidata"

// CIDataInput is the per-VM data Nimbus bakes into the cloud-init
// ISO that gets attached to the clone as a CD-ROM at /dev/sr0.
//
// Unlike Proxmox's auto-generated cloud-init, this ISO is the
// source of truth for what cloud-init runs — no cicustom, no
// snippets storage, no per-deployment config. The entire payload
// is delivered through the same channel (NoCloud CD-ROM) that
// Proxmox itself uses, just with our content instead.
type CIDataInput struct {
	Hostname        string // VM hostname
	Username        string // cloud-init default user (e.g. "ubuntu")
	SSHPublicKey    string // ssh-authorized_keys content (one or many newline-separated)
	ConsolePassword string // one-time chpasswd for noVNC console fallback
	IP              string // static IPv4 (no prefix)
	PrefixLen       int    // CIDR prefix (e.g. 24)
	Gateway         string // static IPv4 gateway
	Nameservers     []string
}

// BuildCIDataISO renders a NoCloud-format ISO9660 image carrying
// user-data, meta-data, and network-config files. Returns the ISO
// bytes ready to be uploaded as `content=iso` to a PVE storage and
// attached as a CD-ROM at ide2 (or any free slot).
//
// The user-data installs qemu-guest-agent on first boot so
// WaitForIP's agent path can confirm readiness — same fix we've
// been chasing through the cicustom/vendor-data paths, just
// delivered through a channel that doesn't depend on a
// snippets-content storage.
func BuildCIDataISO(in CIDataInput) ([]byte, error) {
	w, err := iso9660.NewWriter()
	if err != nil {
		return nil, fmt.Errorf("iso writer: %w", err)
	}
	defer w.Cleanup() //nolint:errcheck

	userData := buildCIUserData(in)
	metaData := buildCIMetaData(in)
	networkConfig := buildCINetworkConfig(in)

	if err := w.AddFile(strings.NewReader(userData), "user-data"); err != nil {
		return nil, fmt.Errorf("add user-data: %w", err)
	}
	if err := w.AddFile(strings.NewReader(metaData), "meta-data"); err != nil {
		return nil, fmt.Errorf("add meta-data: %w", err)
	}
	if err := w.AddFile(strings.NewReader(networkConfig), "network-config"); err != nil {
		return nil, fmt.Errorf("add network-config: %w", err)
	}

	var buf bytes.Buffer
	if err := w.WriteTo(&buf, CIDataLabel); err != nil {
		return nil, fmt.Errorf("write iso: %w", err)
	}
	return buf.Bytes(), nil
}

// buildCIUserData renders the cloud-init user-data YAML. Includes:
//
//   - hostname (canonical)
//   - the cloud-init default user (sudoer, key-only login, but with a
//     one-time random password for noVNC console fallback)
//   - qemu-guest-agent install + enable, so Proxmox's WaitForIP
//     agent path can confirm readiness — the whole reason we're
//     replacing Proxmox's auto cloud-init in the first place.
//
// cloud-init module ordering: `package-update-upgrade-install`
// runs first in cloud_final_modules, then `runcmd` (via
// cc_scripts_user) — so the package install happens before the
// systemctl call.
func buildCIUserData(in CIDataInput) string {
	var keys strings.Builder
	for _, line := range strings.Split(strings.TrimSpace(in.SSHPublicKey), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// Single-quote and escape — defensive even though pubkeys
		// don't contain quotes in practice.
		quoted := strings.ReplaceAll(line, "'", "''")
		fmt.Fprintf(&keys, "      - '%s'\n", quoted)
	}

	return fmt.Sprintf(`#cloud-config
# Auto-generated by Nimbus per provision. Delivered via the cloud-init
# NoCloud datasource (CD-ROM at /dev/sr0); the Cloud-Init tab in PVE
# is decorative for VMs created by Nimbus — edits there will not apply.
hostname: %s
manage_etc_hosts: true
users:
  - name: %s
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
%s
chpasswd:
  expire: false
  list: |
    %s:%s
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - [ systemctl, enable, --now, qemu-guest-agent.service ]
`,
		in.Hostname,
		in.Username,
		strings.TrimRight(keys.String(), "\n"),
		in.Username, in.ConsolePassword,
	)
}

// buildCIMetaData renders the NoCloud meta-data file. cloud-init
// requires `instance-id` (changing it triggers re-running per-instance
// modules). We use the hostname + a short random suffix so a
// re-provisioned VM with the same hostname looks like a different
// instance to cloud-init.
func buildCIMetaData(in CIDataInput) string {
	return fmt.Sprintf("instance-id: nimbus-%s-%s\nlocal-hostname: %s\n",
		in.Hostname, shortRandomSuffix(), in.Hostname)
}

// buildCINetworkConfig renders the cloud-init network-config v2
// payload. We use a wildcard interface match (`name: "e*"`) instead
// of a specific name so the same config works across cloud images
// regardless of whether the kernel names the NIC eth0 / ens18 /
// enp0s3.
func buildCINetworkConfig(in CIDataInput) string {
	prefix := in.PrefixLen
	if prefix == 0 {
		prefix = 24
	}
	var ns strings.Builder
	for _, server := range in.Nameservers {
		s := strings.TrimSpace(server)
		if s == "" {
			continue
		}
		fmt.Fprintf(&ns, "        - %s\n", s)
	}
	if ns.Len() == 0 {
		ns.WriteString("        - 1.1.1.1\n")
	}

	return fmt.Sprintf(`version: 2
ethernets:
  primary:
    match:
      name: "e*"
    dhcp4: false
    addresses:
      - %s/%d
    gateway4: %s
    nameservers:
      addresses:
%s`,
		in.IP, prefix, in.Gateway, strings.TrimRight(ns.String(), "\n"))
}

// shortRandomSuffix returns 6 hex chars from crypto/rand. Used to
// salt cloud-init's instance-id so re-provisions (same hostname,
// different VM) get distinct identities and cloud-init re-runs
// per-instance modules. Falls back to "00000000" on the
// vanishingly-rare crypto/rand error — instance-id collisions are
// non-fatal (cloud-init will just skip per-instance modules,
// matching the pre-cloud-init-was-here-before behavior).
func shortRandomSuffix() string {
	var b [3]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "00000000"
	}
	return hex.EncodeToString(b[:])
}

// generateConsolePassword returns a 16-char hex string suitable for
// a one-time noVNC console login password. crypto/rand failure
// returns "" so the caller can either retry or fall back to no
// password.
func generateConsolePassword() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(b[:])
}

// vmISOFilename is the per-VM cloud-init ISO name. Stable across
// reboots (keyed off vmid, not hostname) so the storage volid stays
// valid for the VM's lifetime; cleaned up when the VM is destroyed.
func vmISOFilename(vmid int) string {
	return fmt.Sprintf("nimbus-vm-%d.iso", vmid)
}
