package provision

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/kdomanski/iso9660"
)

// CIDataLabel is the volume label cloud-init's NoCloud datasource
// scans for. Must be exactly "cidata" (or "CIDATA") for cloud-init
// to find the ISO. We use lowercase to match Proxmox's convention.
const CIDataLabel = "cidata"

// CIDataInput is the per-VM data Nimbus bakes into the cloud-init
// ISO that gets attached to the clone as a CD-ROM at /dev/sr0.
//
// Unlike Proxmox's auto-generated cloud-init, this ISO is the
// source of truth for what cloud-init runs — no cicustom, no
// snippets storage, no per-deployment config. The entire payload
// is delivered through the same channel (NoCloud CD-ROM) that
// Proxmox itself uses, just with our content instead.
type CIDataInput struct {
	Hostname        string // VM hostname
	Username        string // cloud-init default user (e.g. "ubuntu")
	SSHPublicKey    string // ssh-authorized_keys content (one or many newline-separated)
	ConsolePassword string // one-time chpasswd for noVNC console fallback
	IP              string // static IPv4 (no prefix)
	PrefixLen       int    // CIDR prefix (e.g. 24)
	Gateway         string // static IPv4 gateway
	Nameservers     []string
}

// BuildCIDataISO renders a NoCloud-format ISO9660 image carrying
// user-data, meta-data, and network-config files. Returns the ISO
// bytes ready to be uploaded as `content=iso` to a PVE storage and
// attached as a CD-ROM at ide2 (or any free slot).
//
// The user-data installs qemu-guest-agent on first boot so
// WaitForIP's agent path can confirm readiness — same fix we've
// been chasing through the cicustom/vendor-data paths, just
// delivered through a channel that doesn't depend on a
// snippets-content storage.
func BuildCIDataISO(in CIDataInput) ([]byte, error) {
	w, err := iso9660.NewWriter()
	if err != nil {
		return nil, fmt.Errorf("iso writer: %w", err)
	}
	defer w.Cleanup() //nolint:errcheck

	userData := buildCIUserData(in)
	metaData := buildCIMetaData(in)
	networkConfig := buildCINetworkConfig(in)

	if err := w.AddFile(strings.NewReader(userData), "user-data"); err != nil {
		return nil, fmt.Errorf("add user-data: %w", err)
	}
	if err := w.AddFile(strings.NewReader(metaData), "meta-data"); err != nil {
		return nil, fmt.Errorf("add meta-data: %w", err)
	}
	if err := w.AddFile(strings.NewReader(networkConfig), "network-config"); err != nil {
		return nil, fmt.Errorf("add network-config: %w", err)
	}

	var buf bytes.Buffer
	if err := w.WriteTo(&buf, CIDataLabel); err != nil {
		return nil, fmt.Errorf("write iso: %w", err)
	}
	return buf.Bytes(), nil
}

// buildCIUserData renders the cloud-init user-data YAML. Includes:
//
//   - hostname (canonical)
//   - the cloud-init default user (sudoer, key-only login, but with a
//     one-time random password for noVNC console fallback)
//   - qemu-guest-agent install + enable, so Proxmox's WaitForIP
//     agent path can confirm readiness — the whole reason we're
//     replacing Proxmox's auto cloud-init in the first place.
//
// cloud-init module ordering: `package-update-upgrade-install`
// runs first in cloud_final_modules, then `runcmd` (via
// cc_scripts_user) — so the package install happens before the
// systemctl call.
func buildCIUserData(in CIDataInput) string {
	var keys strings.Builder
	for _, line := range strings.Split(strings.TrimSpace(in.SSHPublicKey), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// Single-quote and escape — defensive even though pubkeys
		// don't contain quotes in practice.
		quoted := strings.ReplaceAll(line, "'", "''")
		fmt.Fprintf(&keys, "      - '%s'\n", quoted)
	}

	return fmt.Sprintf(`#cloud-config
# Auto-generated by Nimbus per provision. Delivered via the cloud-init
# NoCloud datasource (CD-ROM at /dev/sr0); the Cloud-Init tab in PVE
# is decorative for VMs created by Nimbus — edits there will not apply.
hostname: %s
manage_etc_hosts: true
users:
  - name: %s
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
%s
chpasswd:
  expire: false
  list: |
    %s:%s
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - [ systemctl, enable, --now, qemu-guest-agent.service ]
`,
		in.Hostname,
		in.Username,
		strings.TrimRight(keys.String(), "\n"),
		in.Username, in.ConsolePassword,
	)
}

// buildCIMetaData renders the NoCloud meta-data file. cloud-init
// requires `instance-id` (changing it triggers re-running per-instance
// modules). We use the hostname + a short random suffix so a
// re-provisioned VM with the same hostname looks like a different
// instance to cloud-init.
func buildCIMetaData(in CIDataInput) string {
	return fmt.Sprintf("instance-id: nimbus-%s-%s\nlocal-hostname: %s\n",
		in.Hostname, shortRandomSuffix(), in.Hostname)
}

// buildCINetworkConfig renders the cloud-init network-config v2
// payload. We use a wildcard interface match (`name: "e*"`) instead
// of a specific name so the same config works across cloud images
// regardless of whether the kernel names the NIC eth0 / ens18 /
// enp0s3.
func buildCINetworkConfig(in CIDataInput) string {
	prefix := in.PrefixLen
	if prefix == 0 {
		prefix = 24
	}
	var ns strings.Builder
	for _, server := range in.Nameservers {
		s := strings.TrimSpace(server)
		if s == "" {
			continue
		}
		fmt.Fprintf(&ns, "        - %s\n", s)
	}
	if ns.Len() == 0 {
		ns.WriteString("        - 1.1.1.1\n")
	}

	return fmt.Sprintf(`version: 2
ethernets:
  primary:
    match:
      name: "e*"
    dhcp4: false
    addresses:
      - %s/%d
    gateway4: %s
    nameservers:
      addresses:
%s`,
		in.IP, prefix, in.Gateway, strings.TrimRight(ns.String(), "\n"))
}

// shortRandomSuffix returns 6 hex chars from crypto/rand. Used to
// salt cloud-init's instance-id so re-provisions (same hostname,
// different VM) get distinct identities and cloud-init re-runs
// per-instance modules. Falls back to "00000000" on the
// vanishingly-rare crypto/rand error — instance-id collisions are
// non-fatal (cloud-init will just skip per-instance modules,
// matching the pre-cloud-init-was-here-before behavior).
func shortRandomSuffix() string {
	var b [3]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "00000000"
	}
	return hex.EncodeToString(b[:])
}

// generateConsolePassword returns a short, human-typeable passphrase
// suitable for one-time noVNC console login. Format: two short
// English words joined by hyphens, followed by four digits — e.g.
// `cedar-otter-4827`. ~28 bits of entropy, far more than enough for
// a single-use console fallback (the password is discarded the
// moment the operator pastes it once and is replaced on the next
// reprovision).
//
// Rationale for not using hex: noVNC console doesn't support
// paste-from-clipboard reliably, so operators end up typing the
// password by hand. Two short words plus four digits is fast to
// type, easy to verbalize ("cedar-otter forty-eight twenty-seven")
// and dramatically reduces typo retries vs a 16-char hex string.
//
// crypto/rand failure returns "" so the caller can fall back to no
// password without crashing (provisioning still succeeds; console
// login just won't work).
func generateConsolePassword() string {
	w1, ok1 := pickPassphraseWord()
	w2, ok2 := pickPassphraseWord()
	digits, ok3 := pickFourDigits()
	if !ok1 || !ok2 || !ok3 {
		return ""
	}
	return fmt.Sprintf("%s-%s-%s", w1, w2, digits)
}

// pickPassphraseWord returns a uniformly random word from
// passphraseWords. The slice is sized so the modulo bias is < 0.4%
// (negligible for a one-time password).
func pickPassphraseWord() (string, bool) {
	var b [2]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", false
	}
	idx := (uint16(b[0])<<8 | uint16(b[1])) % uint16(len(passphraseWords))
	return passphraseWords[idx], true
}

// pickFourDigits returns a 4-digit decimal string, e.g. "0427".
func pickFourDigits() (string, bool) {
	var b [2]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", false
	}
	n := (uint16(b[0])<<8 | uint16(b[1])) % 10000
	return fmt.Sprintf("%04d", n), true
}

// passphraseWords is a curated list of short, common, unambiguous
// English words. 4-6 chars, no homophones (no `cell/sell`, no
// `four/for`), no profanity, no offensive terms. Sized to a power
// of two would let us drop the modulo bias guard, but ~256 makes
// the bias < 0.4% which is fine for one-time use.
var passphraseWords = []string{
	"acorn", "amber", "anvil", "apple", "april", "arrow", "aspen", "atlas",
	"badge", "bagel", "baker", "basil", "beach", "berry", "birch", "blaze",
	"bloom", "boots", "brass", "brick", "brook", "broom", "brown", "bunny",
	"cabin", "cable", "candy", "canoe", "cedar", "chalk", "charm", "cherry",
	"chess", "chime", "cider", "cliff", "cloud", "clove", "clover", "coast",
	"cocoa", "comet", "cookie", "copper", "coral", "crane", "creek", "crest",
	"daisy", "dance", "delta", "denim", "diamond", "dolphin", "dover", "dream",
	"eagle", "earth", "easel", "ember", "envoy", "eraser", "fable", "falcon",
	"fancy", "feast", "felt", "fern", "festive", "fiber", "field", "finch",
	"flame", "fleet", "flint", "float", "flora", "flute", "foggy", "forest",
	"frost", "ginger", "glade", "glass", "glitter", "glow", "golf", "grape",
	"grass", "gravel", "gray", "grin", "grove", "happy", "harbor", "haven",
	"hazel", "heart", "hedge", "heron", "hike", "honey", "horse", "hover",
	"island", "ivory", "jade", "jaguar", "jolly", "juniper", "kayak", "kettle",
	"kingdom", "kite", "knot", "lake", "lemon", "linen", "lion", "lotus",
	"lucky", "lunar", "magic", "maple", "marble", "marsh", "meadow", "mellow",
	"melody", "merry", "mint", "misty", "moon", "moss", "mossy", "mountain",
	"music", "needle", "nest", "noble", "north", "oak", "ocean", "olive",
	"onyx", "opal", "orange", "orbit", "otter", "panda", "paper", "patch",
	"peach", "pearl", "pebble", "pecan", "pencil", "petal", "piano", "pine",
	"pixel", "plaid", "plain", "plant", "plum", "polar", "pond", "poppy",
	"prairie", "prism", "puddle", "purple", "puzzle", "quartz", "quiet", "quill",
	"rabbit", "rain", "rapid", "raven", "ribbon", "ridge", "river", "robin",
	"rocket", "rose", "rosy", "rover", "ruby", "rustic", "sable", "saddle",
	"sage", "salad", "salmon", "sand", "sandy", "sapphire", "sapling", "satin",
	"saxon", "scarlet", "shade", "shamrock", "shell", "shore", "silk", "silver",
	"slate", "smile", "snowy", "solar", "spark", "splash", "spring", "sprout",
	"stone", "stork", "stream", "summer", "sunny", "swan", "tango", "teal",
	"tiger", "timber", "tinsel", "topaz", "torch", "trail", "tundra", "twig",
	"vale", "valley", "velvet", "vine", "violet", "walnut", "warm", "water",
	"wave", "wheat", "whisker", "willow", "winter", "wisdom", "wolf", "woodland",
	"wren", "yacht", "yarn", "year", "yew", "zebra", "zenith", "zephyr",
}

// vmISOFilename is the per-VM cloud-init ISO name. Stable across
// reboots (keyed off vmid, not hostname) so the storage volid stays
// valid for the VM's lifetime; cleaned up when the VM is destroyed.
func vmISOFilename(vmid int) string {
	return fmt.Sprintf("nimbus-vm-%d.iso", vmid)
}
