package provision

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"
)

// GPUBootstrapConfig describes what the per-VM GPU env-var bootstrap should
// stamp into a freshly provisioned guest. Empty BaseURL means "no GPU plane
// configured" — the caller skips the bootstrap entirely.
type GPUBootstrapConfig struct {
	BaseURL        string // GX10 inference base URL, e.g. http://gx10.lan:8000
	NimbusGPUAPI   string // e.g. https://nimbus.example.com/api/gpu
	InferenceModel string // optional default model to advertise via GX10_DEFAULT_MODEL
}

// gpuBootstrapTimeout caps the in-guest bootstrap. Much shorter than the
// tunnel bootstrap because we're not waiting on dpkg — just dropping a
// couple of files into the user's homedir.
const gpuBootstrapTimeout = 30 * time.Second

// looksLikeLocalhostURL reports whether the URL's host is one of the
// localhost aliases — those URLs are unreachable from inside a guest VM
// (they'd resolve to the VM's own loopback) so we refuse to bake them
// into the per-VM env. Empty input also returns true so an unset URL is
// treated as "don't bake".
func looksLikeLocalhostURL(url string) bool {
	if url == "" {
		return true
	}
	u := strings.ToLower(url)
	u = strings.TrimPrefix(strings.TrimPrefix(u, "https://"), "http://")
	if i := strings.IndexAny(u, "/?#"); i >= 0 {
		u = u[:i]
	}
	if i := strings.LastIndex(u, ":"); i >= 0 && !strings.Contains(u[:i], ":") {
		u = u[:i]
	}
	return u == "localhost" ||
		strings.HasPrefix(u, "127.") ||
		u == "0.0.0.0" ||
		u == "::1" ||
		u == "[::1]"
}

// runGPUBootstrap drops /home/<user>/.profile.d/nimbus-gpu.sh + ~/bin/gx10
// into a freshly provisioned guest via the qemu-guest-agent — no SSH, no
// L3 reach required. Idempotent: re-running just overwrites the files.
//
// Failures are logged at the call site, not fatal — a VM without the GPU
// env vars still boots and works; users can paste them in manually.
//
// The agent runs commands as root by default. The script writes into
// /home/<user> rather than ~/, since the agent's HOME is /root.
func runGPUBootstrap(ctx context.Context, px AgentRunner, node string, vmid int, user string, gpuCfg GPUBootstrapConfig) error {
	if gpuCfg.BaseURL == "" {
		return errors.New("empty gpu base URL")
	}
	if user == "" {
		return errors.New("empty cloud-init user")
	}

	envFile := strings.TrimRight(gpuCfg.BaseURL, "/") + "/v1"
	model := gpuCfg.InferenceModel
	if model == "" {
		model = "default"
	}
	apiBase := strings.TrimRight(gpuCfg.NimbusGPUAPI, "/")

	// HOME is /root under the agent; reference the cloud-init user's
	// homedir explicitly. chown the dropped files at the end so the
	// user actually owns them on first login.
	script := fmt.Sprintf(`set -e
USER_NAME=%q
USER_HOME=$(getent passwd "$USER_NAME" | cut -d: -f6)
if [ -z "$USER_HOME" ]; then
  echo "user $USER_NAME not found" >&2
  exit 1
fi

mkdir -p "$USER_HOME/.profile.d" "$USER_HOME/bin"

cat > "$USER_HOME/.profile.d/nimbus-gpu.sh" <<'__NIMBUS_GPU__'
# Auto-generated by Nimbus at provision time. Re-runs replace this file.
export OPENAI_BASE_URL=%q
export OPENAI_API_KEY="nimbus-local"
export NIMBUS_GPU_API=%q
export GX10_DEFAULT_MODEL=%q
__NIMBUS_GPU__

# Source profile.d on every login. cloud-init's default user usually has
# ~/.profile sourcing /etc/profile.d but not ~/.profile.d. We add a one-line
# loader that's idempotent.
if ! grep -qs 'profile.d/.*\.sh' "$USER_HOME/.profile" 2>/dev/null; then
  printf '\nfor f in ~/.profile.d/*.sh; do [ -r "$f" ] && . "$f"; done\n' >> "$USER_HOME/.profile"
fi

cat > "$USER_HOME/bin/gx10" <<'__GX10_CLI__'
#!/usr/bin/env bash
# gx10 — submit a GPU job to the Nimbus job queue.
# Usage: gx10 submit <image> -- <command...>
#        gx10 jobs
#        gx10 logs <id>
set -euo pipefail
: "${NIMBUS_GPU_API:?NIMBUS_GPU_API not set; source ~/.profile.d/nimbus-gpu.sh}"

curl_session() {
  curl --fail --show-error --silent -H "Cookie: ${NIMBUS_SESSION:-}" "$@"
}

cmd="${1:-}"
shift || true
case "$cmd" in
  submit)
    image="${1:-}"; shift || true
    if [ -z "$image" ]; then echo "usage: gx10 submit <image> -- <command...>" >&2; exit 1; fi
    if [ "${1:-}" = "--" ]; then shift; fi
    args="$*"
    payload=$(IMG="$image" CMD="$args" python3 -c 'import json,os; print(json.dumps({"image": os.environ["IMG"], "command": os.environ["CMD"]}))')
    curl_session -X POST "$NIMBUS_GPU_API/jobs" -H 'Content-Type: application/json' -d "$payload"
    ;;
  jobs)
    curl_session "$NIMBUS_GPU_API/jobs"
    ;;
  logs)
    id="${1:-}"
    if [ -z "$id" ]; then echo "usage: gx10 logs <id>" >&2; exit 1; fi
    curl_session "$NIMBUS_GPU_API/jobs/$id"
    ;;
  *)
    echo "usage: gx10 {submit|jobs|logs}" >&2
    exit 1
    ;;
esac
__GX10_CLI__
chmod +x "$USER_HOME/bin/gx10"

# Append ~/bin to PATH if it's not already there. Same idempotent guard as
# above so re-running this script doesn't bloat ~/.profile.
if ! grep -qs '\$HOME/bin' "$USER_HOME/.profile" 2>/dev/null; then
  printf '\nexport PATH="$HOME/bin:$PATH"\n' >> "$USER_HOME/.profile"
fi

# The agent runs as root, so everything we just wrote is root-owned.
# Hand it back to the cloud-init user so first-login sources it cleanly.
chown -R "$USER_NAME":"$USER_NAME" "$USER_HOME/.profile.d" "$USER_HOME/bin"
chown "$USER_NAME":"$USER_NAME" "$USER_HOME/.profile"
`, user, envFile, apiBase, model)

	execCtx, cancel := context.WithTimeout(ctx, gpuBootstrapTimeout)
	defer cancel()
	status, err := px.AgentRun(execCtx, node, vmid, []string{"/bin/sh"}, script, tunnelBootstrapPollInterval)
	if err != nil {
		return fmt.Errorf("agent exec: %w", err)
	}
	if status.ExitCode != 0 {
		out := truncateOutput(strings.TrimRight(status.OutData+status.ErrData, "\n"), maxBootstrapOutputBytes)
		return fmt.Errorf("gpu bootstrap exit %d (output: %s)", status.ExitCode, out)
	}
	return nil
}
